In [29]:
import pandas as pd

In [30]:
df = pd.read_csv("../data/1. raw/smoking_prediction.xlsx - smoking_prediction.csv")

In [31]:
df.shape

(50000, 27)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   50000 non-null  int64
 1   gender               50000 non-null  object
 2   age                  50000 non-null  int64
 3   height(cm)           50000 non-null  int64
 4   weight(kg)           50000 non-null  int64
 5   waist(cm)            50000 non-null  float64
 6   eyesight(left)       50000 non-null  float64
 7   eyesight(right)      50000 non-null  float64
 8   hearing(left)        50000 non-null  float64
 9   hearing(right)       50000 non-null  float64
 10  systolic             50000 non-null  float64
 11  relaxation           50000 non-null  float64
 12  fasting blood sugar  50000 non-null  float64
 13  Cholesterol          50000 non-null  float64
 14  triglyceride         50000 non-null  float64
 15  HDL                  50000 non-null  float64
 16  LDL                  50000 non-null  float64
 17  hemoglobin           50000 non-null  float64
 18  Urine protein        50000 non-null  float64
 19  serum creatinine     50000 non-null  float64
 20  AST                  50000 non-null  float64
 21  ALT                  50000 non-null  float64
 22  Gtp                  50000 non-null  float64
 23  oral                 50000 non-null  object
 24  dental caries        50000 non-null  int64
 25  tartar               50000 non-null  object
 26  smoking              50000 non-null  int64
dtypes: float64(18), int64(6), object(3)
memory usage: 10.3+ MB

In [33]:
df.head(10)

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
0,0,F,40,155,60,3.38,0.04,0.04,0.04,0.04,...,0.51,0.04,0.00,0.75,0.79,1.13,Y,0,Y,0
1,1,F,40,160,60,3.38,0.01,0.00,0.04,0.04,...,0.50,0.04,0.00,0.92,0.79,0.75,Y,0,Y,0
2,2,M,55,170,60,3.33,0.01,0.01,0.04,0.04,...,0.63,0.04,0.04,0.88,0.67,0.92,Y,0,N,1
3,3,M,40,165,70,3.67,0.05,0.05,0.04,0.04,...,0.59,0.04,0.04,0.79,1.08,0.75,Y,0,Y,0
4,4,F,40,155,60,3.58,0.04,0.04,0.04,0.04,...,0.50,0.04,0.00,0.67,0.58,0.92,Y,0,N,0
5,5,M,30,180,75,3.54,0.04,0.04,0.04,0.04,...,0.67,0.04,0.04,0.75,1.13,1.38,Y,0,Y,0
6,6,M,40,160,60,3.55,0.04,0.04,0.04,0.04,...,0.71,0.04,0.00,0.88,1.13,1.63,Y,1,Y,1
7,7,M,45,165,90,4.00,0.04,0.04,0.04,0.04,...,0.63,0.04,0.04,1.58,2.96,4.63,Y,0,Y,0
8,9,F,50,150,60,3.54,0.00,0.01,0.04,0.04,...,0.55,0.04,0.01,1.29,1.29,0.58,Y,0,N,0
9,10,M,45,175,75,3.71,0.04,0.04,0.04,0.04,...,0.67,0.04,0.01,1.08,1.00,2.63,Y,0,N,0

In [34]:
df.tail(10)

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
49990,27311,F,40,160,50,3.04,0.00,0.00,0.04,0.04,...,0.50,0.04,0.01,0.92,0.50,0.83,Y,0,Y,0
49991,27314,M,35,170,65,3.29,0.04,0.04,0.04,0.04,...,0.63,0.04,0.04,0.92,0.75,1.25,Y,0,Y,0
49992,27316,M,45,170,65,3.46,0.04,0.01,0.04,0.04,...,0.63,0.04,0.04,1.13,0.71,1.38,Y,0,Y,0
49993,27320,M,25,180,80,3.71,0.05,0.04,0.04,0.04,...,0.67,0.04,0.04,1.08,1.21,2.00,Y,1,Y,0
49994,27329,F,40,160,65,3.17,0.04,0.04,0.04,0.04,...,0.59,0.04,0.00,0.67,0.58,0.63,Y,0,Y,0
49995,27343,M,50,160,55,2.96,0.00,0.01,0.04,0.04,...,0.55,0.04,0.04,0.96,0.58,0.92,Y,0,Y,1
49996,27350,M,30,170,70,3.33,0.05,0.04,0.04,0.04,...,0.63,0.04,0.01,1.08,1.21,0.75,Y,1,Y,1
49997,27351,M,20,165,65,3.54,0.05,0.05,0.04,0.04,...,0.67,0.04,0.01,1.46,1.46,2.92,Y,0,Y,1
49998,27352,F,60,160,45,2.96,0.00,0.00,0.04,0.04,...,0.58,0.04,0.00,0.79,0.67,1.04,Y,1,Y,0
49999,27354,M,45,170,80,4.00,0.05,0.04,0.04,0.04,...,0.63,0.04,0.04,1.17,1.71,2.58,Y,1,N,1

In [35]:
df["dental caries"].unique() # se revisó porque el df.info() lo generó como entero y se verificó que tomaran valores dicotómicos.

array([0, 1])

In [36]:
df.shape

(50000, 27)

In [37]:
df[["dental caries", "gender", "oral", "tartar"]].nunique() # impeccionamos la cardinalidad de columnas que deben tener 1 o 2 valores distintos. Así revisamos errores de formato en algunas columnas

dental caries    2
gender           2
oral             1
tartar           2
dtype: int64

In [38]:
df["oral"].unique() # Verificamos que solo tiene un valor. Por lo que no se considerará en el entrenamiento

array(['Y'], dtype=object)

In [39]:
df["oral"].value_counts()

oral
Y    50000
Name: count, dtype: int64