In [114]:
import pandas as pd
import joblib

In [115]:
df_predic= pd.read_csv("../data/1. raw/smoking_prediction_entrega.xlsx - smoking_prediction.csv ")

In [116]:
df_predic.head()

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar
0,27358,M,25,160,65,3.42,0.05,0.00,0.04,0.04,...,3.04,0.63,0.04,0.01,0.75,0.71,0.71,Y,0,Y
1,27364,M,30,180,80,3.46,0.04,0.01,0.04,0.04,...,4.21,0.59,0.04,0.04,0.79,1.13,1.33,Y,0,N
2,27368,M,55,165,60,3.42,0.00,0.01,0.04,0.04,...,2.04,0.63,0.04,0.01,1.08,1.29,2.00,Y,1,Y
3,27378,M,20,175,75,3.63,0.05,0.05,0.04,0.04,...,3.71,0.63,0.04,0.04,0.83,0.58,0.46,Y,0,N
4,27381,M,25,165,80,3.79,0.04,0.04,0.04,0.04,...,6.63,0.67,0.04,0.04,1.25,1.63,1.96,Y,1,Y

In [117]:
X_predic = df_predic.drop(columns=["ID","oral"])

In [118]:
X_predic

,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,...,HDL,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,dental caries,tartar
0,M,25,160,65,3.42,0.05,0.00,0.04,0.04,5.04,...,1.96,3.04,0.63,0.04,0.01,0.75,0.71,0.71,0,Y
1,M,30,180,80,3.46,0.04,0.01,0.04,0.04,5.38,...,1.50,4.21,0.59,0.04,0.04,0.79,1.13,1.33,0,N
2,M,55,165,60,3.42,0.00,0.01,0.04,0.04,5.25,...,2.13,2.04,0.63,0.04,0.01,1.08,1.29,2.00,1,Y
3,M,20,175,75,3.63,0.05,0.05,0.04,0.04,5.33,...,1.71,3.71,0.63,0.04,0.04,0.83,0.58,0.46,0,N
4,M,25,165,80,3.79,0.04,0.04,0.04,0.04,4.50,...,2.38,6.63,0.67,0.04,0.04,1.25,1.63,1.96,1,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5687,F,40,170,65,3.13,0.01,0.01,0.04,0.04,4.58,...,3.13,4.92,0.50,0.04,0.00,0.58,0.29,0.42,1,Y
5688,F,45,160,50,2.92,0.04,0.04,0.04,0.04,4.21,...,3.04,3.29,0.58,0.04,0.01,0.83,0.50,0.58,0,Y
5689,F,55,160,50,2.84,0.04,0.04,0.04,0.04,4.88,...,3.29,2.63,0.50,0.04,0.00,0.71,0.46,0.50,0,N
5690,M,60,165,60,3.25,0.01,0.04,0.04,0.04,5.54,...,2.00,6.08,0.59,0.04,0.00,0.83,0.79,0.75,0,N
5691,M,55,160,65,3.54,0.01,0.00,0.04,0.04,5.17,...,1.42,6.25,0.63,0.04,0.01,1.08,1.21,1.71,0,Y

In [146]:
#Cargamos los datos preprocesados.
ohe = joblib.load("../data/4. objetos entrenados/ohe.pkl")
scaler = joblib.load("../data/4. objetos entrenados/scaler.pkl")
num_cols = joblib.load("../data/4. objetos entrenados/num_cols.pkl")
cat_cols = joblib.load("../data/4. objetos entrenados/cat_cols.pkl")
feature_columns = joblib.load("../data/4. objetos entrenados/feature_columns.pkl")

In [147]:
X_predic_ohe=ohe.transform(X_predic[cat_cols]) # Aplicamos OHE a lasa columnas categóricas de X_predic

In [148]:
ohe_columns = ohe.get_feature_names_out(cat_cols) # Obtemos los nombres de las columnas creadas por el OneHotEncoder

In [149]:
X_predic_ohe_df = pd.DataFrame(X_predic_ohe, columns=ohe_columns, index=X_predic.index)

In [150]:
X_predic_num = X_predic[num_cols] #Seleccionamos solo las columnas numéricas de X_predic.

In [124]:
X_predic_final = pd.concat([X_predic_num, X_predic_ohe_df], axis=1) # Concatenamos las columnas numéricas con las columnas OHE en un solo DataFrame final

In [125]:
X_predic_final_scaled = X_predic_final.copy() # Generamos una copia de X_predic_final

In [126]:
X_predic_final_scaled[num_cols] = scaler.transform(X_predic_final[num_cols]) #escalamos las variables numéricas

In [127]:
X_predic_final_scaled = X_predic_final_scaled[feature_columns] #aseguramos mismo orden de columnas que en el entrenamiento

In [128]:
X_predic_final_scaled.head()

,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,relaxation,...,Urine protein,serum creatinine,AST,ALT,Gtp,dental caries,gender_F,gender_M,tartar_N,tartar_Y
0,-1.586340,-0.505152,-0.066283,0.015201,0.912589,-1.145527,-0.162899,-0.164429,-0.039991,-0.093231,...,-0.20951,-0.485813,-0.433699,-0.319069,-0.458849,-0.519579,0.0,1.0,0.0,1.0
1,-1.172943,1.669825,1.102897,0.118629,0.497667,-0.735788,-0.162899,-0.164429,0.556137,0.204826,...,-0.20951,1.226505,-0.382711,0.002266,-0.160669,-0.519579,0.0,1.0,1.0,0.0
2,0.894044,0.038592,-0.456009,0.015201,-1.162019,-0.735788,-0.162899,-0.164429,0.328206,0.726427,...,-0.20951,-0.485813,-0.013053,0.124679,0.161559,1.924636,0.0,1.0,0.0,1.0
3,-1.999738,1.126081,0.713170,0.558197,0.912589,0.903166,-0.162899,-0.164429,0.468471,0.825779,...,-0.20951,1.226505,-0.331724,-0.418529,-0.579084,-0.519579,0.0,1.0,1.0,0.0
4,-1.586340,0.038592,1.102897,0.971909,0.497667,0.493428,-0.162899,-0.164429,-0.986781,-0.416127,...,-0.20951,1.226505,0.203643,0.384808,0.142322,1.924636,0.0,1.0,0.0,1.0

In [151]:
model_rf = joblib.load("../models/smoking_model_forest_best.pkl")

In [152]:
model_xgb = joblib.load("../models/smoking_model_xgb_best.pkl")

Predicciones de RandomForest

In [153]:
predic_rf=model_rf.predict(X_predic_final_scaled) # Generamos la predicción del modelo RF con los datos escalados.

In [154]:
resultado_rf=pd.DataFrame({"ID":df_predic["ID"],"smoking_pred_rf":predic_rf}) #Creamos un DataFrame con el ID y la predicción

In [155]:
resultado_rf.head()

      ID  smoking_pred_rf
0  27358                1
1  27364                1
2  27368                1
3  27378                1
4  27381                1

In [156]:
entrega_rf=resultado_rf[["ID","smoking_pred_rf"]]

In [157]:
entrega_rf.to_csv("../predictions_csv/smoking_predictions_rf.csv",index=False) #Exportamos la predicciones en un archivo .csv

Predicciones XGboost

In [158]:
 predic_xgb=model_xgb.predict(X_predic_final_scaled) # Generamos la predicción del modelo XGB con los datos escalados.

In [159]:
resultado_xgb=pd.DataFrame({"ID":df_predic["ID"], "smoking_pred_xgb":predic_xgb}) #Creamos un DataFrame con el ID y la predicción

In [160]:
resultado_xgb.head()

      ID  smoking_pred_xgb
0  27358                 0
1  27364                 1
2  27368                 1
3  27378                 0
4  27381                 1

In [161]:
entrega_xgb=resultado_xgb[["ID","smoking_pred_xgb"]]  #Creamos un DataFrame con el ID y la predicción

In [162]:
entrega_xgb.to_csv("../predictions_csv/smoking_predictions_xgb.csv",index=False)

Coincidencia entre modelos

In [163]:
#unimos las dos  predicciones en un solo DF
compare = resultado_rf.merge(resultado_xgb, on="ID")

In [164]:
compare["coinciden"] = (compare["smoking_pred_rf"] == compare["smoking_pred_xgb"]) # Creamos una columna booleana indicando si ambas predicciones coinciden

In [165]:
compare["coinciden"].value_counts() #Contamos las coincidencias.

coinciden
True     4538
False    1154
Name: count, dtype: int64

In [166]:
porcentaje_coincidencia=compare["coinciden"].mean() #Calculamos el porcentaje de coicidencias.

In [167]:
print(f"Los dos modelos coinciden en el {porcentaje_coincidencia:.2%} de los casos")

Los dos modelos coinciden en el 79.73% de los casos

.csv comparación de los tres modelos

In [168]:
compare.to_csv("../predictions_csv/smoking_predictions_comparacion.csv",index=False) #Exportamos un .csv con ambas predicciones en una.